[package]
name = "hdr10plus_parser"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[dependencies]
bitreader = "0.3.1"
serde = "1.0.84"
serde_json = "1.0.34"
indicatif = "0.11.0"
read-byte-slice = "0.1.2"